# Render slides in CI
permissions: write-all

on:
    push:
        branches: [main, autorender]

jobs:
    render:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install Marp
              run: /home/linuxbrew/.linuxbrew/bin/brew install marp-cli

            - name: Render all slides
              run: python render_slides.py

            - name: Stage changed files
              run: git add .

            - name: Commit changed files
              run: git commit -m "rendered slides"

            - name: Push code to main
              run: git push origin main
